version: "3.3"

services:
  spark-master:
    image: apache/spark:3.4.1
    hostname: spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker-1:
    image: apache/spark:3.4.1
    hostname: spark-worker-1
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=3
      - SPARK_WORKER_MEMORY=6G
      - SPARK_DRIVER_MEMORY=6G
      - SPARK_EXECUTOR_MEMORY=6G
      - SPARK_LOCAL_IP=spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 -m 6g -c 3

  spark-worker-2:
    image: apache/spark:3.4.1
    hostname: spark-worker-2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=6G
      - SPARK_DRIVER_MEMORY=6G
      - SPARK_EXECUTOR_MEMORY=6G
      - SPARK_LOCAL_IP=spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 -m 6g -c 3