# Base image
#FROM openjdk:11-jdk

# Apache Spark version
ENV SPARK_VERSION=3.4.0

# Download and install Apache Spark
RUN apt-get update && \
    apt-get install -y curl && \
    curl -O https://downloads.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3.tgz && \
    tar -xvf spark-$SPARK_VERSION-bin-hadoop3.tgz && \
    mv spark-$SPARK_VERSION-bin-hadoop3 /spark && \
    rm spark-$SPARK_VERSION-bin-hadoop3.tgz

# Set environment variables
ENV SPARK_HOME=/spark
ENV PATH=$PATH:$SPARK_HOME/bin
